### ISSUE TITLE
Enable Spark NLP to run offline

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/phi-annotator-spark-nlp#6]
The Spark NLP session download java packages when it starts.

```
phi-annotator  | Ivy Default Cache set to: /home/nlp/.ivy2/cache
phi-annotator  | The jars for the packages stored in: /home/nlp/.ivy2/jars
phi-annotator  | com.johnsnowlabs.nlp#spark-nlp_2.12 added as a dependency
phi-annotator  | :: resolving dependencies :: org.apache.spark#spark-submit-parent-05666930-f6cd-4d8e-8778-777a83227d76;1.0
phi-annotator  |        confs: [default]
phi-annotator  |        found com.johnsnowlabs.nlp#spark-nlp_2.12;3.1.0 in central
phi-annotator  |        found com.typesafe#config;1.3.0 in central
phi-annotator  |        found org.rocksdb#rocksdbjni;6.5.3 in central
phi-annotator  |        found com.amazonaws#aws-java-sdk-bundle;1.11.603 in central
phi-annotator  |        found com.github.universal-automata#liblevenshtein;3.0.0 in central
phi-annotator  |        found com.google.code.findbugs#annotations;3.0.1 in central
phi-annotator  |        found net.jcip#jcip-annotations;1.0 in central
phi-annotator  |        found com.google.code.findbugs#jsr305;3.0.1 in central
phi-annotator  |        found com.google.protobuf#protobuf-java-util;3.0.0-beta-3 in central
phi-annotator  |        found com.google.protobuf#protobuf-java;3.0.0-beta-3 in central
phi-annotator  |        found com.google.code.gson#gson;2.3 in central
phi-annotator  |        found it.unimi.dsi#fastutil;7.0.12 in central
phi-annotator  |        found org.projectlombok#lombok;1.16.8 in central
phi-annotator  |        found org.slf4j#slf4j-api;1.7.21 in central
phi-annotator  |        found com.navigamez#greex;1.0 in central
phi-annotator  |        found dk.brics.automaton#automaton;1.11-8 in central
phi-annotator  |        found org.json4s#json4s-ext_2.12;3.5.3 in central
phi-annotator  |        found joda-time#joda-time;2.9.5 in central
phi-annotator  |        found org.joda#joda-convert;1.8.1 in central
phi-annotator  |        found com.johnsnowlabs.nlp#tensorflow-cpu_2.12;0.3.1 in central
phi-annotator  |        found net.sf.trove4j#trove4j;3.0.3 in central
phi-annotator  | downloading https://repo1.maven.org/maven2/com/johnsnowlabs/nlp/spark-nlp_2.12/3.1.0/spark-nlp_2.12-3.1.0.jar ...
phi-annotator  |        [SUCCESSFUL ] com.johnsnowlabs.nlp#spark-nlp_2.12;3.1.0!spark-nlp_2.12.jar (972ms)
phi-annotator  | downloading https://repo1.maven.org/maven2/com/typesafe/config/1.3.0/config-1.3.0.jar ...
phi-annotator  |        [SUCCESSFUL ] com.typesafe#config;1.3.0!config.jar(bundle) (10ms)
phi-annotator  | downloading https://repo1.maven.org/maven2/org/rocksdb/rocksdbjni/6.5.3/rocksdbjni-6.5.3.jar ...
phi-annotator  |        [SUCCESSFUL ] org.rocksdb#rocksdbjni;6.5.3!rocksdbjni.jar (682ms)
phi-annotator  | downloading https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.11.603/aws-java-sdk-bundle-1.11.603.jar ...
phi-annotator  |        [SUCCESSFUL ] com.amazonaws#aws-java-sdk-bundle;1.11.603!aws-java-sdk-bundle.jar (2739ms)
phi-annotator  | downloading https://repo1.maven.org/maven2/com/github/universal-automata/liblevenshtein/3.0.0/liblevenshtein-3.0.0.jar ...
phi-annotator  |        [SUCCESSFUL ] com.github.universal-automata#liblevenshtein;3.0.0!liblevenshtein.jar (7ms)
phi-annotator  | downloading https://repo1.maven.org/maven2/com/navigamez/greex/1.0/greex-1.0.jar ...
phi-annotator  |        [SUCCESSFUL ] com.navigamez#greex;1.0!greex.jar (5ms)
phi-annotator  | downloading https://repo1.maven.org/maven2/org/json4s/json4s-ext_2.12/3.5.3/json4s-ext_2.12-3.5.3.jar ...
phi-annotator  |        [SUCCESSFUL ] org.json4s#json4s-ext_2.12;3.5.3!json4s-ext_2.12.jar (8ms)
phi-annotator  | downloading https://repo1.maven.org/maven2/com/johnsnowlabs/nlp/tensorflow-cpu_2.12/0.3.1/tensorflow-cpu_2.12-0.3.1.jar ...
phi-annotator  |        [SUCCESSFUL ] com.johnsnowlabs.nlp#tensorflow-cpu_2.12;0.3.1!tensorflow-cpu_2.12.jar (7232ms)
phi-annotator  | downloading https://repo1.maven.org/maven2/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar ...
phi-annotator  |        [SUCCESSFUL ] net.sf.trove4j#trove4j;3.0.3!trove4j.jar (49ms)
phi-annotator  | downloading https://repo1.maven.org/maven2/com/google/code/findbugs/annotations/3.0.1/annotations-3.0.1.jar ...
phi-annotator  |        [SUCCESSFUL ] com.google.code.findbugs#annotations;3.0.1!annotations.jar (5ms)
phi-annotator  | downloading https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java-util/3.0.0-beta-3/protobuf-java-util-3.0.0-beta-3.jar ...
phi-annotator  |        [SUCCESSFUL ] com.google.protobuf#protobuf-java-util;3.0.0-beta-3!protobuf-java-util.jar(bundle) (6ms)
phi-annotator  | downloading https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java/3.0.0-beta-3/protobuf-java-3.0.0-beta-3.jar ...
phi-annotator  |        [SUCCESSFUL ] com.google.protobuf#protobuf-java;3.0.0-beta-3!protobuf-java.jar(bundle) (45ms)
phi-annotator  | downloading https://repo1.maven.org/maven2/it/unimi/dsi/fastutil/7.0.12/fastutil-7.0.12.jar ...
phi-annotator  |        [SUCCESSFUL ] it.unimi.dsi#fastutil;7.0.12!fastutil.jar (424ms)
phi-annotator  | downloading https://repo1.maven.org/maven2/org/projectlombok/lombok/1.16.8/lombok-1.16.8.jar ...
phi-annotator  |        [SUCCESSFUL ] org.projectlombok#lombok;1.16.8!lombok.jar (32ms)
phi-annotator  | downloading https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.21/slf4j-api-1.7.21.jar ...
phi-annotator  |        [SUCCESSFUL ] org.slf4j#slf4j-api;1.7.21!slf4j-api.jar (6ms)
phi-annotator  | downloading https://repo1.maven.org/maven2/net/jcip/jcip-annotations/1.0/jcip-annotations-1.0.jar ...
phi-annotator  |        [SUCCESSFUL ] net.jcip#jcip-annotations;1.0!jcip-annotations.jar (6ms)
phi-annotator  | downloading https://repo1.maven.org/maven2/com/google/code/findbugs/jsr305/3.0.1/jsr305-3.0.1.jar ...
phi-annotator  |        [SUCCESSFUL ] com.google.code.findbugs#jsr305;3.0.1!jsr305.jar (5ms)
phi-annotator  | downloading https://repo1.maven.org/maven2/com/google/code/gson/gson/2.3/gson-2.3.jar ...
phi-annotator  |        [SUCCESSFUL ] com.google.code.gson#gson;2.3!gson.jar (12ms)
phi-annotator  | downloading https://repo1.maven.org/maven2/dk/brics/automaton/automaton/1.11-8/automaton-1.11-8.jar ...
phi-annotator  |        [SUCCESSFUL ] dk.brics.automaton#automaton;1.11-8!automaton.jar (9ms)
phi-annotator  | downloading https://repo1.maven.org/maven2/joda-time/joda-time/2.9.5/joda-time-2.9.5.jar ...
phi-annotator  |        [SUCCESSFUL ] joda-time#joda-time;2.9.5!joda-time.jar (20ms)
phi-annotator  | downloading https://repo1.maven.org/maven2/org/joda/joda-convert/1.8.1/joda-convert-1.8.1.jar ...
phi-annotator  |        [SUCCESSFUL ] org.joda#joda-convert;1.8.1!joda-convert.jar (8ms)
phi-annotator  | :: resolution report :: resolve 1942ms :: artifacts dl 12293ms
phi-annotator  |        :: modules in use:
phi-annotator  |        com.amazonaws#aws-java-sdk-bundle;1.11.603 from central in [default]
phi-annotator  |        com.github.universal-automata#liblevenshtein;3.0.0 from central in [default]
phi-annotator  |        com.google.code.findbugs#annotations;3.0.1 from central in [default]
phi-annotator  |        com.google.code.findbugs#jsr305;3.0.1 from central in [default]
phi-annotator  |        com.google.code.gson#gson;2.3 from central in [default]
phi-annotator  |        com.google.protobuf#protobuf-java;3.0.0-beta-3 from central in [default]
phi-annotator  |        com.google.protobuf#protobuf-java-util;3.0.0-beta-3 from central in [default]
phi-annotator  |        com.johnsnowlabs.nlp#spark-nlp_2.12;3.1.0 from central in [default]
phi-annotator  |        com.johnsnowlabs.nlp#tensorflow-cpu_2.12;0.3.1 from central in [default]
phi-annotator  |        com.navigamez#greex;1.0 from central in [default]
phi-annotator  |        com.typesafe#config;1.3.0 from central in [default]
phi-annotator  |        dk.brics.automaton#automaton;1.11-8 from central in [default]
phi-annotator  |        it.unimi.dsi#fastutil;7.0.12 from central in [default]
phi-annotator  |        joda-time#joda-time;2.9.5 from central in [default]
phi-annotator  |        net.jcip#jcip-annotations;1.0 from central in [default]
phi-annotator  |        net.sf.trove4j#trove4j;3.0.3 from central in [default]
phi-annotator  |        org.joda#joda-convert;1.8.1 from central in [default]
phi-annotator  |        org.json4s#json4s-ext_2.12;3.5.3 from central in [default]
phi-annotator  |        org.projectlombok#lombok;1.16.8 from central in [default]
phi-annotator  |        org.rocksdb#rocksdbjni;6.5.3 from central in [default]
phi-annotator  |        org.slf4j#slf4j-api;1.7.21 from central in [default]
phi-annotator  |        ---------------------------------------------------------------------
phi-annotator  |        |                  |            modules            ||   artifacts   |
phi-annotator  |        |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
phi-annotator  |        ---------------------------------------------------------------------
phi-annotator  |        |      default     |   21  |   21  |   21  |   0   ||   21  |   21  |
phi-annotator  |        ---------------------------------------------------------------------
phi-annotator  | :: retrieving :: org.apache.spark#spark-submit-parent-05666930-f6cd-4d8e-8778-777a83227d76
```

This error is thrown when Spark NLP is started in a Docker container that does not have access to internet.

```
phi-annotator  | :: loading settings :: url = jar:file:/opt/spark/jars/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
phi-annotator  | Ivy Default Cache set to: /home/nlp/.ivy2/cache
phi-annotator  | The jars for the packages stored in: /home/nlp/.ivy2/jars
phi-annotator  | com.johnsnowlabs.nlp#spark-nlp_2.12 added as a dependency
phi-annotator  | :: resolving dependencies :: org.apache.spark#spark-submit-parent-c984019e-6a17-463f-adce-593f2a3bc3ae;1.0
phi-annotator  |        confs: [default]
phi-annotator  | You probably access the destination server through a proxy server that is not well configured.
phi-annotator  | You probably access the destination server through a proxy server that is not well configured.
phi-annotator  | You probably access the destination server through a proxy server that is not well configured.
phi-annotator  | You probably access the destination server through a proxy server that is not well configured.
phi-annotator  | :: resolution report :: resolve 20184ms :: artifacts dl 0ms
phi-annotator  |        :: modules in use:
phi-annotator  |        ---------------------------------------------------------------------
phi-annotator  |        |                  |            modules            ||   artifacts   |
phi-annotator  |        |       conf       | number| search|dwnlded|evicted|| number|dwnlded|
phi-annotator  |        ---------------------------------------------------------------------
phi-annotator  |        |      default     |   1   |   0   |   0   |   0   ||   0   |   0   |
phi-annotator  |        ---------------------------------------------------------------------
phi-annotator  |
phi-annotator  | :: problems summary ::
phi-annotator  | :::: WARNINGS
phi-annotator  |        Host repo1.maven.org not found. url=https://repo1.maven.org/maven2/com/johnsnowlabs/nlp/spark-nlp_2.12/3.1.0/spark-nlp_2.12-3.1.0.pom
phi-annotator  |
phi-annotator  |        Host repo1.maven.org not found. url=https://repo1.maven.org/maven2/com/johnsnowlabs/nlp/spark-nlp_2.12/3.1.0/spark-nlp_2.12-3.1.0.jar
phi-annotator  |
phi-annotator  |        Host dl.bintray.com not found. url=https://dl.bintray.com/spark-packages/maven/com/johnsnowlabs/nlp/spark-nlp_2.12/3.1.0/spark-nlp_2.12-3.1.0.pom
phi-annotator  |
phi-annotator  |        Host dl.bintray.com not found. url=https://dl.bintray.com/spark-packages/maven/com/johnsnowlabs/nlp/spark-nlp_2.12/3.1.0/spark-nlp_2.12-3.1.0.jar
phi-annotator  |
phi-annotator  |                module not found: com.johnsnowlabs.nlp#spark-nlp_2.12;3.1.0
phi-annotator  |
phi-annotator  |        ==== local-m2-cache: tried
phi-annotator  |
phi-annotator  |          file:/home/nlp/.m2/repository/com/johnsnowlabs/nlp/spark-nlp_2.12/3.1.0/spark-nlp_2.12-3.1.0.pom
phi-annotator  |
phi-annotator  |          -- artifact com.johnsnowlabs.nlp#spark-nlp_2.12;3.1.0!spark-nlp_2.12.jar:
phi-annotator  |
phi-annotator  |          file:/home/nlp/.m2/repository/com/johnsnowlabs/nlp/spark-nlp_2.12/3.1.0/spark-nlp_2.12-3.1.0.jar
phi-annotator  |
phi-annotator  |        ==== local-ivy-cache: tried
phi-annotator  |
phi-annotator  |          /home/nlp/.ivy2/local/com.johnsnowlabs.nlp/spark-nlp_2.12/3.1.0/ivys/ivy.xml
phi-annotator  |
phi-annotator  |          -- artifact com.johnsnowlabs.nlp#spark-nlp_2.12;3.1.0!spark-nlp_2.12.jar:
phi-annotator  |
phi-annotator  |          /home/nlp/.ivy2/local/com.johnsnowlabs.nlp/spark-nlp_2.12/3.1.0/jars/spark-nlp_2.12.jar
phi-annotator  |
phi-annotator  |        ==== central: tried
phi-annotator  |
phi-annotator  |          https://repo1.maven.org/maven2/com/johnsnowlabs/nlp/spark-nlp_2.12/3.1.0/spark-nlp_2.12-3.1.0.pom
phi-annotator  |
phi-annotator  |          -- artifact com.johnsnowlabs.nlp#spark-nlp_2.12;3.1.0!spark-nlp_2.12.jar:
phi-annotator  |
phi-annotator  |          https://repo1.maven.org/maven2/com/johnsnowlabs/nlp/spark-nlp_2.12/3.1.0/spark-nlp_2.12-3.1.0.jar
phi-annotator  |
phi-annotator  |        ==== spark-packages: tried
phi-annotator  |
phi-annotator  |          https://dl.bintray.com/spark-packages/maven/com/johnsnowlabs/nlp/spark-nlp_2.12/3.1.0/spark-nlp_2.12-3.1.0.pom
phi-annotator  |
phi-annotator  |          -- artifact com.johnsnowlabs.nlp#spark-nlp_2.12;3.1.0!spark-nlp_2.12.jar:
phi-annotator  |
phi-annotator  |          https://dl.bintray.com/spark-packages/maven/com/johnsnowlabs/nlp/spark-nlp_2.12/3.1.0/spark-nlp_2.12-3.1.0.jar
phi-annotator  |
phi-annotator  |                ::::::::::::::::::::::::::::::::::::::::::::::
phi-annotator  |
phi-annotator  |                ::          UNRESOLVED DEPENDENCIES         ::
phi-annotator  |
phi-annotator  |                ::::::::::::::::::::::::::::::::::::::::::::::
phi-annotator  |
phi-annotator  |                :: com.johnsnowlabs.nlp#spark-nlp_2.12;3.1.0: not found
phi-annotator  |
phi-annotator  |                ::::::::::::::::::::::::::::::::::::::::::::::
phi-annotator  |
phi-annotator  |
phi-annotator  |
phi-annotator  | :: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
phi-annotator  | Exception in thread "main" java.lang.RuntimeException: [unresolved dependency: com.johnsnowlabs.nlp#spark-nlp_2.12;3.1.0: not found]
phi-annotator  |        at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1420)
phi-annotator  |        at org.apache.spark.deploy.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:54)
phi-annotator  |        at org.apache.spark.deploy.SparkSubmit.prepareSubmitEnvironment(SparkSubmit.scala:308)
phi-annotator  |        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:894)
phi-annotator  |        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
phi-annotator  |        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
phi-annotator  |        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
phi-annotator  |        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1030)
phi-annotator  |        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1039)
phi-annotator  |        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
phi-annotator  | Failed to add operation for POST /api/v1/textContactAnnotations
phi-annotator  | Traceback (most recent call last):
phi-annotator  |   File "openapi_server/__main__.py", line 10, in <module>
phi-annotator  |     app.add_api('openapi.yaml', pythonic_params=True)
phi-annotator  |   File "/usr/local/lib/python3.9/site-packages/connexion/apps/flask_app.py", line 57, in add_api
phi-annotator  |     api = super(FlaskApp, self).add_api(specification, **kwargs)
phi-annotator  |   File "/usr/local/lib/python3.9/site-packages/connexion/apps/abstract.py", line 144, in add_api
phi-annotator  |     api = self.api_cls(specification,
phi-annotator  |   File "/usr/local/lib/python3.9/site-packages/connexion/apis/abstract.py", line 111, in __init__
phi-annotator  |     self.add_paths()
phi-annotator  |   File "/usr/local/lib/python3.9/site-packages/connexion/apis/abstract.py", line 219, in add_paths
phi-annotator  |     self._handle_add_operation_error(path, method, sys.exc_info())
phi-annotator  |   File "/usr/local/lib/python3.9/site-packages/connexion/apis/abstract.py", line 231, in _handle_add_operation_error
phi-annotator  |     raise value.with_traceback(traceback)
phi-annotator  |   File "/usr/local/lib/python3.9/site-packages/connexion/apis/abstract.py", line 209, in add_paths
phi-annotator  |     self.add_operation(path, method)
phi-annotator  |   File "/usr/local/lib/python3.9/site-packages/connexion/apis/abstract.py", line 162, in add_operation
phi-annotator  |     operation = make_operation(
phi-annotator  |   File "/usr/local/lib/python3.9/site-packages/connexion/operations/__init__.py", line 8, in make_operation
phi-annotator  |     return spec.operation_cls.from_spec(spec, *args, **kwargs)
phi-annotator  |   File "/usr/local/lib/python3.9/site-packages/connexion/operations/openapi.py", line 128, in from_spec
phi-annotator  |     return cls(
phi-annotator  |   File "/usr/local/lib/python3.9/site-packages/connexion/operations/openapi.py", line 75, in __init__
phi-annotator  |     super(OpenAPIOperation, self).__init__(
phi-annotator  |   File "/usr/local/lib/python3.9/site-packages/connexion/operations/abstract.py", line 96, in __init__
phi-annotator  |     self._resolution = resolver.resolve(self)
phi-annotator  |   File "/usr/local/lib/python3.9/site-packages/connexion/resolver.py", line 40, in resolve
phi-annotator  |     return Resolution(self.resolve_function_from_operation_id(operation_id), operation_id)
phi-annotator  |   File "/usr/local/lib/python3.9/site-packages/connexion/resolver.py", line 61, in resolve_function_from_operation_id
phi-annotator  |     return self.function_resolver(operation_id)
phi-annotator  |   File "/usr/local/lib/python3.9/site-packages/connexion/utils.py", line 111, in get_function_from_name
phi-annotator  |     module = importlib.import_module(module_name)
phi-annotator  |   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
phi-annotator  |     return _bootstrap._gcd_import(name[level:], package, level)
phi-annotator  |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
phi-annotator  |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
phi-annotator  |   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
phi-annotator  |   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
phi-annotator  |   File "<frozen importlib._bootstrap_external>", line 855, in exec_module
phi-annotator  |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
phi-annotator  |   File "/opt/app/./openapi_server/controllers/text_contact_annotation_controller.py", line 6, in <module>
phi-annotator  |     from openapi_server.spark import spark
phi-annotator  |   File "/opt/app/./openapi_server/spark.py", line 93, in <module>
phi-annotator  |     spark = Spark()
phi-annotator  |   File "/opt/app/./openapi_server/spark.py", line 17, in __init__
phi-annotator  |     self.spark = sparknlp_jsl.start(os.environ['SPARK_LICENSE_SECRET'], params=params)  # noqa: E501
phi-annotator  |   File "/usr/local/lib/python3.9/site-packages/sparknlp_jsl/__init__.py", line 80, in start
phi-annotator  |     return builder.getOrCreate()
phi-annotator  |   File "/usr/local/lib/python3.9/site-packages/pyspark/sql/session.py", line 228, in getOrCreate
phi-annotator  |     sc = SparkContext.getOrCreate(sparkConf)
phi-annotator  |   File "/usr/local/lib/python3.9/site-packages/pyspark/context.py", line 384, in getOrCreate
phi-annotator  |     SparkContext(conf=conf or SparkConf())
phi-annotator  |   File "/usr/local/lib/python3.9/site-packages/pyspark/context.py", line 144, in __init__
phi-annotator  |     SparkContext._ensure_initialized(self, gateway=gateway, conf=conf)
phi-annotator  |   File "/usr/local/lib/python3.9/site-packages/pyspark/context.py", line 331, in _ensure_initialized
phi-annotator  |     SparkContext._gateway = gateway or launch_gateway(conf)
phi-annotator  |   File "/usr/local/lib/python3.9/site-packages/pyspark/java_gateway.py", line 108, in launch_gateway
phi-annotator  |     raise Exception("Java gateway process exited before sending its port number")
phi-annotator  | Exception: Java gateway process exited before sending its port number
phi-annotator  | unable to load app 0 (mountpoint='') (callable not found or import error)
phi-annotator  | *** no app loaded. going in full dynamic mode ***
```

**Comment by tschaffter** [comment]
### TODO

- [x] Follow the Spark NLP instructions to run it offline, see https://nlp.johnsnowlabs.com/docs/en/install#offline

**Comment by tschaffter** [comment]
Done in #3
